# Generated by Django 2.2 on 2020-04-12 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chunked_upload', '0001_initial'),
        ('package', '0004_auto_20200412_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='package/icon/%Y/%m/%d/%H%M%S'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.FileField(upload_to='package/image/%Y/%m/%d/%H%M%S'),
        ),
        migrations.AlterField(
            model_name='packagerequest',
            name='icon',
            field=models.FileField(upload_to='package/icon/%Y/%m/%d/%H%M%S'),
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='file',
            field=models.FileField(upload_to='package/version/%Y/%m/%d/%H%M%S'),
        ),
    ]
