# Generated by Django 2.2 on 2020-04-12 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chunked_upload', '0001_initial'),
        ('package', '0005_auto_20200412_2141'),
    ]

    operations = [
    ]
