# Generated by Django 2.2 on 2020-04-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_auto_20200412_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='homepage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
