# Generated by Django 2.2.10 on 2020-06-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200601_0047'),
        ('package', '0016_remove_packageupload_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageupload',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_uploads', to='customer.Customer'),
        ),
    ]
