# Generated by Django 2.2.24 on 2021-08-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0017_packageupload_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageversion',
            name='ipfs_cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='ipfs_gateway',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
