# Generated by Django 2.2.28 on 2023-02-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0021_package_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='downloads',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
