# Generated by Django 2.2.10 on 2020-06-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertoken',
            name='expired',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
