# Generated by Django 2.2 on 2020-04-12 21:56

import apps.package.model.package
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0009_auto_20200412_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
