# Generated by Django 2.2 on 2020-04-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_auto_20200412_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageversion',
            name='downloads',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
