# Generated by Django 2.2.24 on 2021-08-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0018_auto_20210818_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='package/version/%Y/%m/%d/%H%M%S'),
        ),
    ]
