# Generated by Django 2.2.24 on 2021-11-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0019_auto_20210820_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='repository',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
