# Generated by Django 2.2 on 2020-04-04 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('package', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypackagegroupmember',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='companypackagegroupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyPackageGroup'),
        ),
        migrations.AddField(
            model_name='companypackagegroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company'),
        ),
        migrations.AddField(
            model_name='companypackagegroup',
            name='members',
            field=models.ManyToManyField(through='company.CompanyPackageGroupMember', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='companypackagegroup',
            name='packages',
            field=models.ManyToManyField(through='company.CompanyPackageGroupPackage', to='package.Package'),
        ),
        migrations.AddField(
            model_name='companyinvitecustomer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AddField(
            model_name='companyinvitecustomer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='company',
            name='admins',
            field=models.ManyToManyField(related_name='company_admins', through='customer.CustomerCompanyAdmin', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(related_name='company_members', through='customer.CustomerCompanyMember', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company'),
        ),
    ]
